noun = input("Please input a weird noun: ")
verb = input("Please input a verb ending in -ing: ")
adj = input("Please input a silly adjective: ")
food = input("Please input the name of a food: ")
quantity = input("Please input a quantity: ")
person = input("Please input a famous person: ")
noise = input("Please input a noise: ")
print(" ")
print("On one faitful day, "+person+" finds a "+noun+".")
print("The "+noun+" was "+adj+".")
print("And the "+noun+" started moving!")
print(person+" became very worried!")
print("It started chanting, I want "+quantity+" "+food+"s!")
print("It started to "+verb+" over to the "+food+" on the counter!")
print(noise+"!")
print("I want "+quantity+" "+food+"s!")
print(noise+"!")
print("I want "+quantity+" "+food+"s!")
print(noise+" !")
print("I want "+quantity+" "+food+"s!")
print(person+" was very scared!")
print("Then the "+noun+" started eating the "+food+"!")
print(noise+"!")
print("Yum!")
print(noise+"!")
print("Yum!")
print(noise+"!")
print("Yum!")
print(noise+"!")
print("Yum!")
print("Then finally, the "+noun+" satsfied it's hunger!")
print("The "+ noun+" screamed,'I will return!'")
print("Then the "+noun+" melted into a pile of sludge and disappeared!")